name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        erlang:
          - 1:25.0.4-1
    steps:
      - uses: actions/checkout@v2
      - name: Install Erlang
        run: |
          wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
          sudo dpkg -i erlang-solutions_2.0_all.deb
          sudo apt update
          sudo apt install -y --allow-downgrades esl-erlang=${{ matrix.erlang }}
      - name: Install Elixir
        run: |
          sudo apt install -y elixir=1.13.4-1
      - name: Install RMQ requirements
        run: |
          wget https://github.com/rabbitmq/mix_task_archive_deps/releases/download/0.5.0/mix_task_archive_deps-0.5.0.ez
          mix archive.install --force ./mix_task_archive_deps-0.5.0.ez
          rm mix_task_archive_deps-0.5.0.ez
      - name: Run tests
        run: |
          make tests
